# This is an example of using Composite Run Steps Actions

name: Composite Example

on: 
  push:
    types:
      - opened
      - edited
      - synchronize
    branches: main
jobs:
  copy_files_job:
    runs-on: ubuntu-latest
    name: A job that copy files
    steps:
    - name: semantic-pull-request
      uses: amannn/action-semantic-pull-request@v3.4.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    - uses: actions/checkout@v2
    - name: "Test combine action"
      uses: ./.github/actions/test
      with:
        destinationFolder: '/whatever/folder'
    - run: echo Files copied ${{ steps.myCompositeAction.outputs.copied-files }} 
      shell: bash