# This is an example of using Composite Run Steps Actions

name: Push only

on: 
  push:
    branches: main
jobs:
  copy_files_job:
    runs-on: ubuntu-latest
    name: A job that copy files

    steps:
    - uses: actions/checkout@v2
    - name: "Test combine action"
      uses: ./.github/actions/test
      with:
        destinationFolder: '/whatever/folder'
    - run: echo Files copied ${{ steps.myCompositeAction.outputs.copied-files }} 
      shell: bash