name: Source code changes

on: 
  pull_request:
    types:
        - opened
        - edited
        - synchronize
    branches: main
jobs:
  copy_files_job:
    runs-on: ubuntu-latest
    name: A job that copy files
    steps:
    - name: semantic-pull-request
      uses: amannn/action-semantic-pull-request@v3.4.0
      env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
      with:
          # Configure which types are allowed.
          # Default: https://github.com/commitizen/conventional-commit-types
          types: |
            fix
            feat
          scopes: |
            core
            ui
    - uses: actions/checkout@v2
    - name: "Test combine action"
      uses: ./.github/actions/test
      with:
        destinationFolder: '/whatever/folder'
    - name: Last Step
      if: contains(steps.semantic-pull-request.types, 'feat')
      run: echo Files copied ${{ steps.myCompositeAction.outputs.copied-files }} 
      shell: bash